Repository hashicorp/terraform-azurerm-terraform-enterprise, pull requests merged in 2019-09, with the labels that each got.

#6 move tf to md and add copy for correct display
  examples/basic/README.md
Labels: documentation

#7 re-add terraform file so registry picks up dir
  examples/basic/main.tf
Labels: documentation

#10 Fix modules/common parameter rendering
  modules/common/variables.tf
Labels: bug

#8 Add in CA plumbing for custom certificates
  README.md
  main.tf
  modules/configs/README.md
  modules/configs/cloud-init.tf
  modules/configs/files/install-ptfe.sh
  modules/configs/templates/cloud-init/cloud-config.yaml
  modules/configs/templates/replicated/replicated-ptfe.conf
  modules/configs/variables.tf
  variables.tf
Labels: enhancement
